import { SerializedGraphData } from "@/types";

export const DEFAULT_DEMO_GRAPH: SerializedGraphData = {
  nodes: [
    {
      id: "src/app/page.tsx",
      path: "src/app/page.tsx",
      name: "page.tsx",
      language: "typescript",
      size: 4820,
      inDegree: 0,
      outDegree: 4,
      imports: [
        "src/components/shared/navbar.tsx",
        "src/components/shared/codebase-visualizer.tsx",
        "src/lib/supabase/server.ts",
        "src/lib/profiles.ts",
      ],
      importedBy: [],
    },
    {
      id: "src/components/shared/navbar.tsx",
      path: "src/components/shared/navbar.tsx",
      name: "navbar.tsx",
      language: "typescript",
      size: 3200,
      inDegree: 1,
      outDegree: 2,
      imports: [
        "src/lib/supabase/client.ts",
        "src/components/ui/button.tsx",
      ],
      importedBy: ["src/app/page.tsx"],
    },
    {
      id: "src/components/shared/codebase-visualizer.tsx",
      path: "src/components/shared/codebase-visualizer.tsx",
      name: "codebase-visualizer.tsx",
      language: "typescript",
      size: 14200,
      inDegree: 1,
      outDegree: 3,
      imports: [
        "src/lib/parser/dependency-graph-builder.ts",
        "src/types/index.ts",
        "src/components/ui/button.tsx",
      ],
      importedBy: ["src/app/page.tsx"],
    },
    {
      id: "src/components/repositories/architecture-health-card.tsx",
      path: "src/components/repositories/architecture-health-card.tsx",
      name: "architecture-health-card.tsx",
      language: "typescript",
      size: 4100,
      inDegree: 0,
      outDegree: 2,
      imports: [
        "src/utils/coupling-calculator.ts",
        "src/types/index.ts",
      ],
      importedBy: [],
    },
    {
      id: "src/lib/parser/ast-analyzer.ts",
      path: "src/lib/parser/ast-analyzer.ts",
      name: "ast-analyzer.ts",
      language: "typescript",
      size: 8900,
      inDegree: 1,
      outDegree: 2,
      imports: [
        "src/types/index.ts",
        "src/utils/coupling-calculator.ts",
      ],
      importedBy: ["src/lib/parser/dependency-graph-builder.ts"],
    },
    {
      id: "src/lib/parser/dependency-graph-builder.ts",
      path: "src/lib/parser/dependency-graph-builder.ts",
      name: "dependency-graph-builder.ts",
      language: "typescript",
      size: 6700,
      inDegree: 1,
      outDegree: 2,
      imports: [
        "src/lib/parser/ast-analyzer.ts",
        "src/types/index.ts",
      ],
      importedBy: ["src/components/shared/codebase-visualizer.tsx"],
    },
    {
      id: "src/lib/supabase/client.ts",
      path: "src/lib/supabase/client.ts",
      name: "client.ts",
      language: "typescript",
      size: 1100,
      inDegree: 1,
      outDegree: 0,
      imports: [],
      importedBy: ["src/components/shared/navbar.tsx"],
    },
    {
      id: "src/lib/supabase/server.ts",
      path: "src/lib/supabase/server.ts",
      name: "server.ts",
      language: "typescript",
      size: 1400,
      inDegree: 2,
      outDegree: 0,
      imports: [],
      importedBy: ["src/app/page.tsx", "src/lib/profiles.ts"],
    },
    {
      id: "src/lib/profiles.ts",
      path: "src/lib/profiles.ts",
      name: "profiles.ts",
      language: "typescript",
      size: 2100,
      inDegree: 1,
      outDegree: 2,
      imports: [
        "src/lib/supabase/server.ts",
        "src/types/index.ts",
      ],
      importedBy: ["src/app/page.tsx"],
    },
    {
      id: "src/types/index.ts",
      path: "src/types/index.ts",
      name: "index.ts",
      language: "typescript",
      size: 3800,
      inDegree: 5,
      outDegree: 0,
      imports: [],
      importedBy: [
        "src/components/shared/codebase-visualizer.tsx",
        "src/lib/parser/dependency-graph-builder.ts",
        "src/lib/parser/ast-analyzer.ts",
        "src/lib/profiles.ts",
        "src/components/repositories/architecture-health-card.tsx",
      ],
    },
    {
      id: "src/utils/coupling-calculator.ts",
      path: "src/utils/coupling-calculator.ts",
      name: "coupling-calculator.ts",
      language: "typescript",
      size: 2900,
      inDegree: 2,
      outDegree: 1,
      imports: ["src/types/index.ts"],
      importedBy: [
        "src/lib/parser/ast-analyzer.ts",
        "src/components/repositories/architecture-health-card.tsx",
      ],
    },
    {
      id: "src/components/ui/button.tsx",
      path: "src/components/ui/button.tsx",
      name: "button.tsx",
      language: "typescript",
      size: 1800,
      inDegree: 2,
      outDegree: 0,
      imports: [],
      importedBy: [
        "src/components/shared/navbar.tsx",
        "src/components/shared/codebase-visualizer.tsx",
      ],
    },
  ],
  edges: [
    { id: "e1", source: "src/app/page.tsx", target: "src/components/shared/navbar.tsx", importPath: "@/components/shared/navbar" },
    { id: "e2", source: "src/app/page.tsx", target: "src/components/shared/codebase-visualizer.tsx", importPath: "@/components/shared/codebase-visualizer" },
    { id: "e3", source: "src/app/page.tsx", target: "src/lib/supabase/server.ts", importPath: "@/lib/supabase/server" },
    { id: "e4", source: "src/app/page.tsx", target: "src/lib/profiles.ts", importPath: "@/lib/profiles" },
    { id: "e5", source: "src/components/shared/navbar.tsx", target: "src/lib/supabase/client.ts", importPath: "@/lib/supabase/client" },
    { id: "e6", source: "src/components/shared/navbar.tsx", target: "src/components/ui/button.tsx", importPath: "@/components/ui/button" },
    { id: "e7", source: "src/components/shared/codebase-visualizer.tsx", target: "src/lib/parser/dependency-graph-builder.ts", importPath: "@/lib/parser/dependency-graph-builder" },
    { id: "e8", source: "src/components/shared/codebase-visualizer.tsx", target: "src/types/index.ts", importPath: "@/types" },
    { id: "e9", source: "src/components/shared/codebase-visualizer.tsx", target: "src/components/ui/button.tsx", importPath: "@/components/ui/button" },
    { id: "e10", source: "src/lib/parser/dependency-graph-builder.ts", target: "src/lib/parser/ast-analyzer.ts", importPath: "./ast-analyzer" },
    { id: "e11", source: "src/lib/parser/ast-analyzer.ts", target: "src/types/index.ts", importPath: "@/types" },
    { id: "e12", source: "src/lib/parser/ast-analyzer.ts", target: "src/utils/coupling-calculator.ts", importPath: "@/utils/coupling-calculator" },
    { id: "e13", source: "src/lib/profiles.ts", target: "src/lib/supabase/server.ts", importPath: "@/lib/supabase/server" },
    { id: "e14", source: "src/lib/profiles.ts", target: "src/types/index.ts", importPath: "@/types" },
    { id: "e15", source: "src/components/repositories/architecture-health-card.tsx", target: "src/utils/coupling-calculator.ts", importPath: "@/utils/coupling-calculator" },
    { id: "e16", source: "src/components/repositories/architecture-health-card.tsx", target: "src/types/index.ts", importPath: "@/types" },
  ],
  summary: {
    filesProcessed: 12,
    internalDependencies: 16,
    externalDependencies: 6,
    unresolvedDependencies: 0,
    circularDependencyCount: 0,
    mostImportedFiles: [
      { path: "src/types/index.ts", count: 5 },
      { path: "src/lib/supabase/server.ts", count: 2 },
      { path: "src/components/ui/button.tsx", count: 2 },
    ],
    mostDependentFiles: [
      { path: "src/app/page.tsx", count: 4 },
      { path: "src/components/shared/codebase-visualizer.tsx", count: 3 },
      { path: "src/lib/parser/ast-analyzer.ts", count: 2 },
    ],
    externalPackages: [
      { name: "react", count: 1 },
      { name: "next", count: 2 },
      { name: "lucide-react", count: 3 },
    ],
    circularCycles: [],
  },
};
